//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogTime.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogTime.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogTime - Error de autenticación.
        /// </summary>
        internal static string AUTH_ERROR_TITLE {
            get {
                return ResourceManager.GetString("AUTH_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las credenciales no son validas..
        /// </summary>
        internal static string CREDENTIALS_ERROR {
            get {
                return ResourceManager.GetString("CREDENTIALS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar la actividad de Break antes de que transcurran 2 minutos podría generar inconsistencias en el registro de la actividad. ¿Deseas continuar?.
        /// </summary>
        internal static string EARLY_BREAK_CHANGE {
            get {
                return ResourceManager.GetString("EARLY_BREAK_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogTime - Cambio de Break .
        /// </summary>
        internal static string EARLY_BREAK_TITLE {
            get {
                return ResourceManager.GetString("EARLY_BREAK_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de inactividad límite alcanzado. .
        /// </summary>
        internal static string IDLE_TIMER_LIMIT_INFO {
            get {
                return ResourceManager.GetString("IDLE_TIMER_LIMIT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una sesión iniciada con el usuario {0} en la PC {1} ¿Deseas continuar para cerrar esa sesión?.
        /// </summary>
        internal static string OPEN_SESSION_MESSAGE {
            get {
                return ResourceManager.GetString("OPEN_SESSION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogTime - Sesión ya iniciada.
        /// </summary>
        internal static string OPEN_SESSION_TITLE {
            get {
                return ResourceManager.GetString("OPEN_SESSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En estos momentos, su acceso a la aplicación está restringido. Si considera que esto es un error, por favor contacte a su supervisor..
        /// </summary>
        internal static string RESTRICTED_ACCESS {
            get {
                return ResourceManager.GetString("RESTRICTED_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogTime - Sin acceso.
        /// </summary>
        internal static string RESTRICTED_ACCESS_TITLE {
            get {
                return ResourceManager.GetString("RESTRICTED_ACCESS_TITLE", resourceCulture);
            }
        }
    }
}
